apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSW4zMDdCM1hQNTB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1qQXhNRE00TXpCYUZ3MHpOVEF6TVRneE1EUXpNekJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURKRGUrNmdjZVZEbnRGdWwvT2N6Wmw5d09GWjhqNWdKVTF0N1k0b1VnSE1UUTUwZks5bnFia2JyQU0KYzZKb2FjS09MODMyUWpiOTJTZVBMaWFNbFA0NVhTUE1oWCsrZkF2eSs3a1cxZitGcTYrTm5icUJYUGhsN2FTSApraElJdC9mV3NsRzNQdVNrektMRjZ2NlNjcExhdkp6Q09wWVh4b2ovVVpkN2tSeTN0ZEFGbVRUZE05Wi9rYWFJCmJzMVIrN2NWaVFuZkQ2aEFpVjFrTGFyMFlBN1pYYzBZaUxrUXZKWjlEcjdSY21raENhUHNyZGpyUVovd3VJL2UKMzRMQW1yemRpZC9MK3NDdURVdkRBR2pyUE9od21uREc3N3dZMGNlMVRqK3E5U0k2VXgxTHpkTWV2N2JGTlkwNQpzVHRyTXlIRHBMdGMzcWpWTlJaVXJzOUtnZFJyQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSVllXS0hlalc3UkRJa3RkSDZGSTNiNjlGVVVEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXl2OVFBOGlSdQpBcVY2dTlYejg3ajVIY2gvRituaHBaRisyQjVwNGlaWHJGOEtqeWNXTGhWdWUvek1HaVNmVEdhb2p6NUhhOXJRCnVjdXdWYVFVVitrek5uaSs4Z29YS3I5VWd5bjhiMGladFpBVGZSYzJLakxwYzcvYUEzV1JtSVJQRXFRd3VONXoKVEt4NFh3a3ZCeFhTellEbGdsQkhjT0FUeDlLa3dQc3dmdmEzRHdEVmJiRkxmUnpRTWFndzFPMDV3UDBKWUVHMgo5U2V5cFk0cDFFd2NIdmRnempFNGR5U3lJeVFkRjZTVjZISG91dHkyZHErVndWRWFEdEZicytOUmpUeXk0S1BJCmRxUG5JN2tJbndIV2RFeGFCdDlKd1doeGU4aHdqV1hUclUrQ0JuZUFyd1I0T1BXVTVRSC9lMnhucC9FQ054L3EKT2lwVEtIMjZRVHJWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://39DBD33FE85547DAD806DB934A8546BB.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:784866907805:cluster/my-eks
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:784866907805:cluster/my-eks
    user: arn:aws:eks:us-east-2:784866907805:cluster/my-eks
  name: arn:aws:eks:us-east-2:784866907805:cluster/my-eks
current-context: arn:aws:eks:us-east-2:784866907805:cluster/my-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:784866907805:cluster/my-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - my-eks
      - --output
      - json
      command: aws
